version: 0.2.3.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
build:
  project: nDiscUtils.sln
  verbosity: detailed
after_build:
- ps: |
    $platform = $env:PLATFORM
    $configuration = $env:CONFIGURATION
    $name = "ndiscutils-$platform.exe"
    Push-AppveyorArtifact (Resolve-Path ./bin/$platform/$configuration/$name) -FileName $name
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: nDiscUtils $(appveyor_build_version)
  auth_token:
    secure: Dk5VMb+gcTeoyDHWS4Vi1g09ps2PrW7ohAOB/FWnC5DLNZSukUPCPgT+QQLgcoP0
  repository: Lukas0610/nDiscUtils
  artifact: /.*\.exe/