version: 0.4.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
build:
  project: nDiscUtils.sln
  verbosity: detailed
before_build:
  - nuget restore
after_build:
- ps: |
    $platform = $env:PLATFORM
    $configuration = $env:CONFIGURATION
    Push-AppveyorArtifact ./bin/$platform/$configuration/ndiscutils.exe -FileName ndiscutils-$platform.exe
# deploy:
# - provider: GitHub
#   tag: v$(appveyor_build_version)
#   release: nDiscUtils $(appveyor_build_version)
#   auth_token:
#     secure: Dk5VMb+gcTeoyDHWS4Vi1g09ps2PrW7ohAOB/FWnC5DLNZSukUPCPgT+QQLgcoP0
#   repository: Lukas0610/nDiscUtils
#   artifact: /.*\.exe/